//Login

export const AUTH_STARTED = 'AUTH_STARTED';
export const VERIFY_OTP = 'VERIFY_OTP';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const SET_USER = 'SET_USER';

//Log out
export const LOG_OUT = 'LOG_OUT';
export const RESET_STUDENTS = 'RESET_STUDENTS';

//Accounts
export const CREATE_ACCOUNT_STARTED = 'CREATE_ACCOUNT_STARTED';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

export const SET_STUDENT_STATES = 'SET_STUDENT_SETS';
export const SET_STUDENT_DISTRICT = 'SET_STUDENT_DISTRICT';
export const SET_STUDENT_TAL = 'SET_STUDENT_TAL';

export const GET_SCHOOL_STARTED = 'GET_SCHOOL_STARTED';
export const SET_SCHOOL = 'SET_SCHOOL';

export const SET_STATES = 'SET_STATES';
export const SET_BOARDS = 'SET_BOARDS';
export const SET_DISTRICTS = 'SET_DISTRICTS';
export const SET_MEDIUM = 'SET_MEDIUM';
export const SET_CLASSES = 'SET_CLASSES';

export const CREATE_STUDENT_STARTED = 'CREATE_STUDENT_STARTED';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAILED = 'CREATE_STUDENT_FAILED';

export const GET_STUDENTS_STARTED = 'GET_STUDENTS_STARTED';
export const GET_STUDENTS_FAILED = 'GET_STUDENTS_FAILED';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';

export const GET_SUBJECTS_STARTED = 'GET_SUBJECTS_STARTED';
export const GET_SUBJECTS_FAILED = 'GET_SUBJECTS_FAILED';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';

export const GET_CHAPTERS_STARTED = 'GET_CHAPTERS_STARTED';
export const GET_CHAPTERS_FAILED = 'GET_CHAPTERS_FAILED';
export const GET_CHAPTERS_SUCCESS = 'GET_CHAPTERS_SUCCESS';

export const CHAPTER_PREVIEW_STARTED = 'CHAPTER_PREVIEW_STARTED';
export const CHAPTER_PREVIEW_FAILED = 'CHAPTER_PREVIEW_FAILED';
export const CHAPTER_PREVIEW_SUCCESS = 'CHAPTER_PREVIEW_SUCCESS';

export const CHAPTER_PART_STARTED = 'CHAPTER_PART_STARTED';
export const CHAPTER_PART_FAILED = 'CHAPTER_PART_FAILED';
export const CHAPTER_PART_SUCCESS = 'CHAPTER_PART_SUCCESS';

//account
export const SET_ACTIVE_STUDENT = 'SET_ACTIVE_STUDENT';

export const GET_CHAPTER_PART_TIME_SPENT_STARTED =
  'GET_CHAPTER_PART_TIME_SPENT_STARTED';
export const GET_CHAPTER_PART_TIME_SPENT = 'GET_CHAPTER_PART_TIME_SPENT';
export const GET_CHAPTER_PART_TIME_SPENT_FAILED =
  'GET_CHAPTER_PART_TIME_SPENT_FAILED';

export const UPDATE_PROFILE_STARTED = 'UPDATE_PROFILE_STARTED';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const RESET_PROFILE_UPDATE = 'RESET_PROFILE_UPDATE';

export const DELETE_PROFILE_STARTED = 'DELETE_PROFILE_STARTED';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';
export const DELETE_PROFILE_ERROR = 'DELETE_PROFILE_ERROR';

export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const UPDATE_PROFILE_PICTURE_ERROR = 'UPDATE_PROFILE_PICTURE_ERROR';
export const UPDATE_PROFILE_PICTURE_SUCCESS = 'UPDATE_PROFILE_PICTURE_SUCCESS';

export const RESET_DEL_ACTION = 'RESET_DEL_ACTION';

export const BOOKMARK_CHAPTER = 'BOOKMARK_CHAPTER';
export const BOOKMARK_CHAPTER_SUCCESS = 'BOOKMARK_CHAPTER_SUCCESS';
export const BOOKMARK_CHAPTER_RESET = 'BOOKMARK_CHAPTER_RESET';
export const BOOKMARK_CHAPTER_FAIL = 'BOOKMARK_CHAPTER_FAIL';

export const GET_BOOKMARK_CHAPTER_STARTED = 'GET_BOOKMARK_CHAPTER_STARTED';
export const GET_BOOKMARK_CHAPTER_SUCCESS = 'GET_BOOKMARK_CHAPTER_SUCCESS';
export const GET_BOOKMARK_CHAPTER_FAILED = 'GET_BOOKMARK_CHAPTER_FAILED';

export const SYNC_CHAPTERS = 'SYNC_CHAPTERS';

export const SET_DOWNLOAD_CHAPTERS = 'SET_DOWNLOAD_CHAPTERS';
export const SET_DOWNLOAD_CHAPTERS_FETCHED = 'SET_DOWNLOAD_CHAPTERS_FETCHED';

export const GET_TOTAL_TIME_SPENT = 'GET_TOTAL_TIME_SPENT';

export const SET_DOWNLOAD_STARTED = 'SET_DOWNLOAD_STARTED';
export const SET_DOWNLOAD_FINISHED = 'SET_DOWNLOAD_FINISHED';
export const SET_DOWNLOAD_PROGRESS = 'SET_DOWNLOAD_PROGRESS';

export const SET_USER_EXISTED = 'SET_USER_EXISTED';

export const COMMENT_STARTED = 'COMMENT_STARTED';
export const COMMENT_FAILED = 'COMMENT_FAILED';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';

export const GET_ALL_COMMENTS_STARTED = 'GET_ALL_COMMENTS_STARTED';
export const GET_ALL_COMMENTS_FAILED = 'GET_ALL_COMMENTS_FAILED';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';

export const GET_ALL_NOTIFICATIONS_STARTED = 'GET_ALL_NOTIFICATIONS_STARTED';
export const GET_ALL_NOTIFICATIONS_FAILED = 'GET_ALL_NOTIFICATIONS_FAILED';
export const GET_ALL_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';

export const GET_DAILY_ACTIVITY_STARTED = 'GET_DAILY_ACTIVITY_STARTED';
export const GET_DAILY_ACTIVITY_FAILED = 'GET_DAILY_ACTIVITY_FAILED';
export const GET_DAILY_ACTIVITY_SUCCESS = 'GET_DAILY_ACTIVITY_SUCCESS';

export const GET_LEADER_BOARD_STARTED = 'GET_LEADER_BOARD_STARTED';
export const GET_LEADER_BOARD_FAILED = 'GET_LEADER_BOARD_FAILED';
export const GET_LEADER_BOARD_SUCCESS = 'GET_LEADER_BOARD_SUCCESS';
export const GET_LEADERBOARD_STATE_TOPPERS = 'GET_LEADERBOARD_STATE_TOPPERS';

export const GET_CLASSMATES_STARTED = 'GET_CLASSMATES_STARTED';
export const GET_CLASSMATES_FAILED = 'GET_CLASSMATES_FAILED';
export const GET_CLASSMATES_SUCCESS = 'GET_CLASSMATES_SUCCESS';

export const GET_USER_TIME_TRACKING_STARTED = 'GET_USER_TIME_TRACKING_STARTED';
export const GET_USER_TIME_TRACKING_FAILED = 'GET_USER_TIME_TRACKING_FAILED';
export const GET_USER_TIME_TRACKING_SUCCESS = 'GET_USER_TIME_TRACKING_SUCCESS';

export const SET_PDF_GEN_STARTED = 'SET_PDF_GEN_STARTED';
export const SET_PDF_GEN_FINISHED = 'SET_PDF_GEN_FINISHED';

export const GET_TIME_STARTED = 'GET_TIME_STARTED';
export const GET_TIME_FAILED = 'GET_TIME_FAILED';
export const GET_TIME_SUCCESS = 'GET_TIME_SUCCESS';

export const GET_ACCOUNT_INFO_STARTED = 'GET_ACCOUNT_INFO_STARTED';
export const GET_ACCOUNT_INFO_FAILED = 'GET_ACCOUNT_INFO_FAILED';
export const GET_ACCOUNT_INFO_SUCCESS = 'GET_ACCOUNT_INFO_SUCCESS';

export const GET_STUDENTS_EXCEL_DATA = 'GET_STUDENTS_EXCEL_DATA';
export const GET_STUDENTS_EXCEL_DATA_FAILED = 'GET_STUDENTS_EXCEL_DATA_FAILED';

export const SET_ALL_SCHOOLS = 'SET_ALL_SCHOOLS';

export const GET_APP_VERSION = "GET_APP_VERSION";
export const SET_APP_VERSION = "SET_APP_VERSION";

export const APP_VERSION_UPDATE_SUCCESS = "APP_VERSION_UPDATE_SUCCESS";
export const APP_VERSION_UPDATE_FAILED = "APP_VERSION_UPDATE_FAILED";

export const CHAPTER_RATING_FAILED = "CHAPTER_RATING_FAILED";
export const CHAPTER_RATING_SUCCESS = "CHAPTER_RATING_SUCCESS";
export const RESET_CHAPTER_RATING = "RESET_CHAPTER_RATING";

export const SET_CHAPTER_REVIEW = "SET_CHAPTER_REVIEW";

export const BOOKMARK_DELETE_SUCCESS = "BOOKMARK_DELETE_SUCCESS";
export const BOOKMARK_DELETE_FAILED = "BOOKMARK_DELETE_FAILED";

export const SET_APP_BACKGROUND = "SET_APP_BACKGROUND";
export const IS_SET_BACKGROUND = "IS_SET_BACKGROUND";

export const SET_CHAPTER_DOWNLOADED = "SET_CHAPTER_DOWNLOADED";
export const RESET_CHAPTER_DOWNLOADED = "RESET_CHAPTER_DOWNLOADED";

export const SET_SCHOOL_DATA = "SET_SCHOOL_DATA";

export const SET_IS_SPECIAL_COURSE_VIEWED = "SET_IS_SPECIAL_COURSE_VIEWED";

export const SET_COURSE_NAME = "SET_COURSE_NAME";

export const SET_MCQ_FORPART = "SET_MCQ_FORPART";

export const GET_MCQ_ATTEMPT = "GET_MCQ_ATTEMPT";

export const GET_MCQ_SUMMARY = "GET_MCQ_SUMMARY"
